-- Pixel Art Highlight Definitions
local M = {}

function M.setup(c, opts)
  local bg = opts.transparent and "NONE" or c.bg
  local bg_float = (opts.transparent and opts.styles.floats == "transparent") and "NONE" or c.bg_float
  local bg_sidebar = (opts.transparent and opts.styles.sidebars == "transparent") and "NONE" or c.bg_dark

  local hl = {
    -- Editor UI
    Normal = { fg = c.fg, bg = bg },
    NormalNC = { fg = c.fg, bg = bg },
    NormalFloat = { fg = c.fg, bg = bg_float },
    FloatBorder = { fg = c.border, bg = bg_float },
    FloatTitle = { fg = c.cyan, bg = bg_float, bold = true },
    Cursor = { fg = c.bg, bg = c.cyan },
    CursorLine = { bg = c.bg_highlight },
    CursorColumn = { bg = c.bg_highlight },
    ColorColumn = { bg = c.bg_highlight },
    LineNr = { fg = c.fg_gutter },
    CursorLineNr = { fg = c.yellow, bold = true },
    SignColumn = { fg = c.fg_gutter, bg = bg },
    VertSplit = { fg = c.border },
    WinSeparator = { fg = c.border, bold = true },
    StatusLine = { fg = c.fg, bg = c.bg_highlight },
    StatusLineNC = { fg = c.fg_dark, bg = c.bg_dark },
    TabLine = { fg = c.fg_dark, bg = c.bg_dark },
    TabLineSel = { fg = c.bg, bg = c.cyan, bold = true },
    TabLineFill = { bg = c.bg_dark },
    Pmenu = { fg = c.fg, bg = c.bg_float },
    PmenuSel = { fg = c.bg, bg = c.cyan, bold = true },
    PmenuSbar = { bg = c.bg_highlight },
    PmenuThumb = { bg = c.border },
    WildMenu = { fg = c.bg, bg = c.cyan },
    Search = { fg = c.bg, bg = c.yellow },
    IncSearch = { fg = c.bg, bg = c.pink, bold = true },
    CurSearch = { fg = c.bg, bg = c.pink, bold = true },
    Visual = { bg = c.bg_selection },
    VisualNOS = { bg = c.bg_selection },
    MatchParen = { fg = c.yellow, bg = c.bg_highlight, bold = true },
    Directory = { fg = c.cyan, bold = true },
    ErrorMsg = { fg = c.red, bold = true },
    WarningMsg = { fg = c.orange, bold = true },
    ModeMsg = { fg = c.green, bold = true },
    MoreMsg = { fg = c.cyan, bold = true },
    Question = { fg = c.green },
    NonText = { fg = c.fg_gutter },
    SpecialKey = { fg = c.fg_gutter },
    Folded = { fg = c.fg_dark, bg = c.bg_highlight },
    FoldColumn = { fg = c.fg_gutter, bg = bg },
    Title = { fg = c.cyan, bold = true },
    Conceal = { fg = c.fg_dark },
    SpellBad = { sp = c.red, undercurl = true },
    SpellCap = { sp = c.yellow, undercurl = true },
    SpellRare = { sp = c.cyan, undercurl = true },
    SpellLocal = { sp = c.green, undercurl = true },

    -- Standard Syntax
    Comment = { fg = c.fg_dark, italic = opts.styles.comments.italic },
    Constant = { fg = c.yellow },
    String = { fg = c.green },
    Character = { fg = c.green },
    Number = { fg = c.yellow },
    Boolean = { fg = c.yellow, bold = true },
    Float = { fg = c.yellow },
    Identifier = { fg = c.fg },
    Function = { fg = c.cyan, bold = opts.styles.functions.bold },
    Statement = { fg = c.pink, bold = opts.styles.keywords.bold },
    Conditional = { fg = c.pink, bold = opts.styles.keywords.bold },
    Repeat = { fg = c.pink, bold = opts.styles.keywords.bold },
    Label = { fg = c.pink },
    Operator = { fg = c.pink },
    Keyword = { fg = c.pink, bold = opts.styles.keywords.bold },
    Exception = { fg = c.red, bold = true },
    PreProc = { fg = c.purple },
    Include = { fg = c.pink },
    Define = { fg = c.purple },
    Macro = { fg = c.purple },
    PreCondit = { fg = c.purple },
    Type = { fg = c.orange, bold = true },
    StorageClass = { fg = c.orange },
    Structure = { fg = c.orange },
    Typedef = { fg = c.orange },
    Special = { fg = c.cyan },
    SpecialChar = { fg = c.yellow },
    Tag = { fg = c.pink },
    Delimiter = { fg = c.fg },
    SpecialComment = { fg = c.fg_dark, bold = true },
    Debug = { fg = c.red },
    Underlined = { underline = true },
    Ignore = { fg = c.fg_gutter },
    Error = { fg = c.red, bold = true },
    Todo = { fg = c.bg, bg = c.yellow, bold = true },

    -- Treesitter
    ["@variable"] = { fg = c.fg },
    ["@variable.builtin"] = { fg = c.red },
    ["@variable.parameter"] = { fg = c.orange },
    ["@variable.member"] = { fg = c.fg },
    ["@constant"] = { fg = c.yellow },
    ["@constant.builtin"] = { fg = c.yellow, bold = true },
    ["@constant.macro"] = { fg = c.purple },
    ["@string"] = { fg = c.green },
    ["@string.regex"] = { fg = c.yellow },
    ["@string.escape"] = { fg = c.pink },
    ["@character"] = { fg = c.green },
    ["@number"] = { fg = c.yellow },
    ["@boolean"] = { fg = c.yellow, bold = true },
    ["@float"] = { fg = c.yellow },
    ["@function"] = { fg = c.cyan, bold = opts.styles.functions.bold },
    ["@function.builtin"] = { fg = c.cyan },
    ["@function.call"] = { fg = c.cyan },
    ["@function.macro"] = { fg = c.purple },
    ["@method"] = { fg = c.cyan },
    ["@method.call"] = { fg = c.cyan },
    ["@constructor"] = { fg = c.orange },
    ["@parameter"] = { fg = c.orange },
    ["@keyword"] = { fg = c.pink, bold = opts.styles.keywords.bold },
    ["@keyword.function"] = { fg = c.pink, bold = opts.styles.keywords.bold },
    ["@keyword.operator"] = { fg = c.pink },
    ["@keyword.return"] = { fg = c.pink, bold = true },
    ["@conditional"] = { fg = c.pink },
    ["@repeat"] = { fg = c.pink },
    ["@label"] = { fg = c.pink },
    ["@operator"] = { fg = c.pink },
    ["@exception"] = { fg = c.red },
    ["@type"] = { fg = c.orange, bold = true },
    ["@type.builtin"] = { fg = c.orange },
    ["@type.definition"] = { fg = c.orange },
    ["@type.qualifier"] = { fg = c.pink },
    ["@storageclass"] = { fg = c.orange },
    ["@attribute"] = { fg = c.purple },
    ["@field"] = { fg = c.fg },
    ["@property"] = { fg = c.fg },
    ["@punctuation.delimiter"] = { fg = c.fg },
    ["@punctuation.bracket"] = { fg = c.fg_dark },
    ["@punctuation.special"] = { fg = c.pink },
    ["@comment"] = { fg = c.fg_dark, italic = opts.styles.comments.italic },
    ["@tag"] = { fg = c.pink },
    ["@tag.attribute"] = { fg = c.cyan },
    ["@tag.delimiter"] = { fg = c.fg_dark },

    -- Diagnostics / LSP
    DiagnosticError = { fg = c.red },
    DiagnosticWarn = { fg = c.orange },
    DiagnosticInfo = { fg = c.cyan },
    DiagnosticHint = { fg = c.green },
    DiagnosticUnderlineError = { sp = c.red, underline = true },
    DiagnosticUnderlineWarn = { sp = c.orange, underline = true },
    DiagnosticUnderlineInfo = { sp = c.cyan, underline = true },
    DiagnosticUnderlineHint = { sp = c.green, underline = true },

    -- Git Signs / Diffs
    DiffAdd = { bg = c.diff_add },
    DiffChange = { bg = c.diff_change },
    DiffDelete = { bg = c.diff_delete },
    DiffText = { fg = c.bg, bg = c.yellow },
    GitSignsAdd = { fg = c.green },
    GitSignsChange = { fg = c.orange },
    GitSignsDelete = { fg = c.red },

    -- NvimTree
    NvimTreeNormal = { fg = c.fg, bg = bg_sidebar },
    NvimTreeNormalNC = { fg = c.fg, bg = bg_sidebar },
    NvimTreeRootFolder = { fg = c.cyan, bold = true },
    NvimTreeFolderName = { fg = c.cyan },
    NvimTreeOpenedFolderName = { fg = c.cyan, bold = true },
    NvimTreeEmptyFolderName = { fg = c.fg_dark },
    NvimTreeSpecialFile = { fg = c.yellow, bold = true },
    NvimTreeImageFile = { fg = c.pink },
    NvimTreeIndentMarker = { fg = c.fg_gutter },
    NvimTreeGitDirty = { fg = c.orange },
    NvimTreeGitNew = { fg = c.green },
    NvimTreeGitDeleted = { fg = c.red },
    NvimTreeWindowPicker = { fg = c.bg, bg = c.cyan, bold = true },
    NvimTreeCursorLine = { bg = c.bg_highlight },

    -- Nvim CMP
    CmpItemAbbr = { fg = c.fg },
    CmpItemAbbrDeprecated = { fg = c.fg_dark, strikethrough = true },
    CmpItemAbbrMatch = { fg = c.cyan, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.cyan, bold = true },
    CmpItemMenu = { fg = c.fg_dark },
    CmpItemKind = { fg = c.pink },
    CmpItemKindFunction = { fg = c.cyan },
    CmpItemKindMethod = { fg = c.cyan },
    CmpItemKindVariable = { fg = c.orange },
    CmpItemKindKeyword = { fg = c.pink },
    CmpItemKindSnippet = { fg = c.yellow },
    CmpItemKindText = { fg = c.fg },

    -- Alpha Dashboard
    AlphaHeader = { fg = c.cyan, bold = true },
    AlphaButtons = { fg = c.pink },
    AlphaShortcut = { fg = c.yellow, bold = true },
    AlphaFooter = { fg = c.fg_dark },

    -- ToggleTerm
    ToggleTermNormal = { fg = c.fg, bg = bg },
    ToggleTermBorder = { fg = c.border },

    -- Telescope
    TelescopeBorder = { fg = c.border, bg = bg_float },
    TelescopePromptBorder = { fg = c.border_focus, bg = bg_float },
    TelescopeResultsBorder = { fg = c.border, bg = bg_float },
    TelescopePreviewBorder = { fg = c.border, bg = bg_float },
    TelescopePromptTitle = { fg = c.bg, bg = c.cyan, bold = true },
    TelescopeResultsTitle = { fg = c.bg, bg = c.pink, bold = true },
    TelescopePreviewTitle = { fg = c.bg, bg = c.green, bold = true },
    TelescopeSelection = { bg = c.bg_highlight },
    TelescopeMatching = { fg = c.yellow, bold = true },

    -- WhichKey
    WhichKey = { fg = c.cyan, bold = true },
    WhichKeyGroup = { fg = c.pink },
    WhichKeyDesc = { fg = c.fg },
    WhichKeySeparator = { fg = c.fg_dark },
  }

  for group, attrs in pairs(hl) do
    vim.api.nvim_set_hl(0, group, attrs)
  end
end

return M
